map_id: imported_pcd_map
frame_id: map
resolution: 0.1
octomap_file: octomap_msg.npz
layers_file: layers.npz
source_world_file: ''
snapshot_stamp:
  sec: 1788161870
  nanosec: 351018364
bounds:
  min:
  - -2.8
  - -4.1
  - -0.4
  max:
  - 5.9
  - 1.7000000000000002
  - 0.4
planner:
  robot_radius: 0.25
  snap_search_radius_cells: 12
  require_ground_support: true
  strict_direct_ground_support: false
  ground_support_xy_radius_cells: 1
  ground_support_depth_cells: 1
  enable_preblocked_costmap: true
  preblocked_costmap_radius_cells: 3
  preblocked_costmap_weight: 2.5
layers:
  preblocked_count: 6693
  traversable_count: 436
  risk_cost_count: 436
